# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 859a0f4a3143aca8284de1d3ceaac6917eaff0e3512f522b94cd8211024b87868fccc61c505a6fea04854be6f96912dffdec1b5c317a0fd60155a49b09bde6c6

test:
  secret_key_base: ae19a49792eab281302b7ca6a0975de3488c5e405ec5d33f44c3e5c987e7a6e98ddfb26d2fdd7de6719c39922e051afa1ec0c71d525df8de76bf1b43901cc44d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
